package org.aksw.fox.tools.re.common.boa;

/**
 *
 * @author Ren&eacute; Speck <speck@informatik.uni-leipzig.de>
 *
 */
public enum BoaEnum {

  URI("uri"),

  NLR_GEN("nlr-gen"),

  NLR_VAR("nlr-var"),

  NLR_NO_VAR("nlr-no-var"),

  BOA_SCORE("boa-score"),

  DOMAIN("domain"),

  RANGE("range"),

  GOOD_PLACE_DOMAIN("GOOD_PLACE_DOMAIN"),

  WORDNET_DISTANCE("WORDNET_DISTANCE"),

  AVERAGE_TOKEN_LENGHT("AVERAGE_TOKEN_LENGHT"),

  TYPICITY_SENTENCES("TYPICITY_SENTENCES"),

  UPPERCASE_LETTER_COUNT("UPPERCASE_LETTER_COUNT"),

  TF_IDF_IDF("TF_IDF_IDF"),

  LEVENSHTEIN("LEVENSHTEIN"),

  SUPPORT_NUMBER_OF_PAIRS_LEARNED_FROM("SUPPORT_NUMBER_OF_PAIRS_LEARNED_FROM"),

  TOTAL_OCCURRENCE("TOTAL_OCCURRENCE"),

  POSSESSIVE("POSSESSIVE"),

  TF_IDF_TF("TF_IDF_TF"),

  POS_REGEX_1("POS_REGEX_1"),

  POS_REGEX_2("POS_REGEX_2"),

  POS_REGEX_3("POS_REGEX_3"),

  SPECIFICITY("SPECIFICITY"),

  NON_ALPHA_SPACE_COUNT("NON_ALPHA_SPACE_COUNT"),

  SUPPORT_NUMBER_OF_MAX_PAIRS_LEARNED_FROM("SUPPORT_NUMBER_OF_MAX_PAIRS_LEARNED_FROM"),

  COMMA_COUNT("COMMA_COUNT"),

  CHARACTER_COUNT("CHARACTER_COUNT"),

  TYPICITY_CORRECT_RANGE_NUMBER("TYPICITY_CORRECT_RANGE_NUMBER"),

  VERB_COUNT("VERB_COUNT"),

  GOOD_PLACE_RANGE("GOOD_PLACE_RANGE"),

  SPECIFICITY_OCCURRENCE("SPECIFICITY_OCCURRENCE"),

  SINGLE_NOUN("SINGLE_NOUN"),

  TOKEN_COUNT("TOKEN_COUNT"),

  TYPICITY_CORRECT_DOMAIN_NUMBER("TYPICITY_CORRECT_DOMAIN_NUMBER"),

  REVERB("REVERB"),

  TF_IDF_TFIDF("TF_IDF_TFIDF"),

  NNP_COUNT("NNP_COUNT"),

  DIGIT_COUNT("DIGIT_COUNT"),

  TYPICITY("TYPICITY"),

  GENERALIZED("generalized"),

  POS("pos"),

  LEARNEDFROM("learnedfrom"),

  MAXLEARNEDFROM("maxlearnedfrom");

  private final String label;

  private BoaEnum(final String label) {
    this.label = label;
  }

  public String getLabel() {
    return label;
  }
}
